version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:17.0  # You can change this version if needed

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Verify Java Version
          command: java -version
      - run:
          name: Install Maven
          command: |
            sudo apt update
            sudo apt install -y maven
      - run:
          name: Build with Maven
          command: mvn clean install
